In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)




In [2]:
adult_df=pd.read_csv(r'adult_data.csv',
                     header=None,delimiter=' *, *')#this delimeter will allow you to remove the extra padded sapces around all the fields
adult_df.head()



0                 1       2          3   4                   5   \
0  39         State-gov   77516  Bachelors  13       Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13  Married-civ-spouse   
2  38           Private  215646    HS-grad   9            Divorced   
3  53           Private  234721       11th   7  Married-civ-spouse   
4  28           Private  338409  Bachelors  13  Married-civ-spouse   

                  6              7      8       9     10  11  12  \
0       Adm-clerical  Not-in-family  White    Male  2174   0  40   
1    Exec-managerial        Husband  White    Male     0   0  13   
2  Handlers-cleaners  Not-in-family  White    Male     0   0  40   
3  Handlers-cleaners        Husband  Black    Male     0   0  40   
4     Prof-specialty           Wife  Black  Female     0   0  40   

              13     14  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [3]:
adult_df.shape 

(32561, 15)

In [4]:
adult_df.columns=['age','workclass','fnlwgt','education','education_num',
                  'marital status','occupation','relationship',
                  'race','sex','capital gain','capital_loss',
                  'hours_per_week','native_country','income']


In [5]:
adult_df.head()

age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital gain  capital_loss  hours_per_week native_country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

# Pre processing the data 

In [6]:
#create a copy of dataframe
adult_df_rev=pd.DataFrame.copy(adult_df)

In [7]:
adult_df_rev=adult_df_rev.drop(["education","fnlwgt"],axis=1)


In [8]:
adult_df_rev.shape

(32561, 13)

In [9]:
adult_df_rev.isnull().sum()# atleast a numerical variable might not be having a  missing value. 

age               0
workclass         0
education_num     0
marital status    0
occupation        0
relationship      0
race              0
sex               0
capital gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [10]:
for i in adult_df_rev.columns:
    print({i:adult_df_rev[i].unique()}) # here we are manually check is their any special characters in dataset 

{'age': array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43,
       54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
       46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
       26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
       83, 84, 85, 86, 87], dtype=int64)}
{'workclass': array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)}
{'education_num': array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8],
      dtype=int64)}
{'marital status': array(['Never-married', 'Married-civ-spouse', 'Divorced',
       'Married-spouse-absent', 'Separated', 'Married-AF-spouse',
       'Widowed'], dtype=object)}
{'occupation': array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing'

In [11]:
adult_df_rev.dtypes

age                int64
workclass         object
education_num      int64
marital status    object
occupation        object
relationship      object
race              object
sex               object
capital gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [12]:
adult_df_rev=adult_df_rev.replace(["?"],np.nan) 

In [13]:
adult_df_rev.isnull().sum()

age                  0
workclass         1836
education_num        0
marital status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [14]:
#replace the missing values with mode values
for value in ['workclass','occupation','native_country']:
    adult_df_rev[value].fillna(adult_df_rev[value].mode()[0],inplace=True )

In [15]:
adult_df_rev.workclass.mode()[0]

'Private'

In [16]:
adult_df_rev.isnull().sum()

age               0
workclass         0
education_num     0
marital status    0
occupation        0
relationship      0
race              0
sex               0
capital gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [17]:
"""
for x in adult_df_rev.columns:
    if adult df_rev[x].dtype =='object'or adult_df_rev[x].dtype =='bool':
         adult_df_rev[x].fillna(adult_df_rev[x].mode()[0],inplace=True
    elif adult_df_rev[x].dtype =='int64'or adult_df_rev[x].dtype =='float64':
         adult_df_rev[x].fillna(adult_df_rev[x].mean(),inplace=True) 
"""


"\nfor x in adult_df_rev.columns:\n    if adult df_rev[x].dtype =='object'or adult_df_rev[x].dtype =='bool':\n         adult_df_rev[x].fillna(adult_df_rev[x].mode()[0],inplace=True\n    elif adult_df_rev[x].dtype =='int64'or adult_df_rev[x].dtype =='float64':\n         adult_df_rev[x].fillna(adult_df_rev[x].mean(),inplace=True) \n"

In [18]:
adult_df_rev.workclass.value_counts()

Private             24532
Self-emp-not-inc     2541
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [19]:
colname=[]
for x in adult_df_rev.columns:
    if adult_df_rev[x].dtype=='object':
        colname.append(x)
colname        
                    

['workclass',
 'marital status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [20]:
#for preprocessing the data
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
"""
-It will try storing all of the unique values from that (colname)
variable as the key and it will try associating numeric value 
along with it.
-Those number values that assign, are going to be in ascending order.
"""
for x in colname:
    adult_df_rev[x]=le.fit_transform(adult_df_rev[x])
    
    le_name_mapping=dict(zip(le.classes_, le.transform(le.classes_)))
    print('feature',x)
    print('mapping',le_name_mapping)

feature workclass
mapping {'Federal-gov': 0, 'Local-gov': 1, 'Never-worked': 2, 'Private': 3, 'Self-emp-inc': 4, 'Self-emp-not-inc': 5, 'State-gov': 6, 'Without-pay': 7}
feature marital status
mapping {'Divorced': 0, 'Married-AF-spouse': 1, 'Married-civ-spouse': 2, 'Married-spouse-absent': 3, 'Never-married': 4, 'Separated': 5, 'Widowed': 6}
feature occupation
mapping {'Adm-clerical': 0, 'Armed-Forces': 1, 'Craft-repair': 2, 'Exec-managerial': 3, 'Farming-fishing': 4, 'Handlers-cleaners': 5, 'Machine-op-inspct': 6, 'Other-service': 7, 'Priv-house-serv': 8, 'Prof-specialty': 9, 'Protective-serv': 10, 'Sales': 11, 'Tech-support': 12, 'Transport-moving': 13}
feature relationship
mapping {'Husband': 0, 'Not-in-family': 1, 'Other-relative': 2, 'Own-child': 3, 'Unmarried': 4, 'Wife': 5}
feature race
mapping {'Amer-Indian-Eskimo': 0, 'Asian-Pac-Islander': 1, 'Black': 2, 'Other': 3, 'White': 4}
feature sex
mapping {'Female': 0, 'Male': 1}
feature native_country
mapping {'Cambodia': 0, 'Canada'

In [21]:

adult_df_rev.head(10)
#<=50K: 0 
#>50K: 1


age  workclass  education_num  marital status  occupation  relationship  \
0   39          6             13               4           0             1   
1   50          5             13               2           3             0   
2   38          3              9               0           5             1   
3   53          3              7               2           5             0   
4   28          3             13               2           9             5   
5   37          3             14               2           3             5   
6   49          3              5               3           7             1   
7   52          5              9               2           3             0   
8   31          3             14               4           9             1   
9   42          3             13               2           3             0   

   race  sex  capital gain  capital_loss  hours_per_week  native_country  \
0     4    1          2174             0              40              38   
1     4    1             0             0              13              38   
2     4    1             0             0              40              38   
3     2    1             0             0              40              38   
4     2    0             0             0              40               4   
5     4    0             0             0              40              38   
6     2    0             0             0              16              22   
7     4    1             0             0              45              38   
8     4    0         14084             0              50              38   
9     4    1          5178             0              40              38   

   income  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       1  
8       1  
9       1

In [22]:
adult_df_rev.dtypes

age               int64
workclass         int32
education_num     int64
marital status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [23]:
X=adult_df_rev.values[:,0:-1] #--> 0 to -2
Y=adult_df_rev.values[:,-1]

In [24]:
X.shape

(32561, 12)

In [25]:
Y.shape

(32561,)

In [26]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)

X=scaler.transform(X)

print(X)



[[ 0.03067056  2.62429763  1.13473876 ... -0.21665953 -0.03542945
   0.26136999]
 [ 0.83710898  1.72109965  1.13473876 ... -0.21665953 -2.22215312
   0.26136999]
 [-0.04264203 -0.08529633 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]
 ...
 [ 1.42360965 -0.08529633 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]
 [-1.21564337 -0.08529633 -0.42005962 ... -0.21665953 -1.65522476
   0.26136999]
 [ 0.98373415  0.81790166 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]]


In [27]:
Y=Y.astype(int)

# Runnig a basic model

In [28]:
from sklearn.model_selection import train_test_split

#split the data  into test and train 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                                 random_state=10)
                                   

In [29]:
from sklearn.linear_model import LogisticRegression
#creating a model
classifier=LogisticRegression()

#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))



[(0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 1), (0, 0), (0, 0), (1, 0), (1, 1), (1, 0), (0, 0), (1, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (1, 0), (0, 0), (0, 0), (1, 0), (1, 1), (0, 1), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (1, 0), (0, 0), (0, 1), (1, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (1, 1), (1, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),

In [30]:
"""
if you want to checkout what is the intercept and the slope coef value
"""

#print(list(zip(adult_df_rev.columns[:-1],classifier.coef_.ravel())))
#print(classifier.intercept_)
"""
-here i am just trying to print the intercpet and  the slope coef value,
and zipping them with the column names because if i don't zip with column names
it will be difficult to relate for which variable the slope coef value is assign.

"""


"\n-here i am just trying to print the intercpet and  the slope coef value,\nand zipping them with the column names because if i don't zip with column names\nit will be difficult to relate for which variable the slope coef value is assign.\n\n"

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[7017  406]
 [1316 1030]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7423
           1       0.72      0.44      0.54      2346

    accuracy                           0.82      9769
   macro avg       0.78      0.69      0.72      9769
weighted avg       0.81      0.82      0.81      9769

Accuracy of the model :  0.8237281195618794


# Adjusting the threshold

In [32]:
#store the predicted probabilities
y_pred_prob=classifier.predict_proba(X_test)
y_pred_prob

array([[0.96864499, 0.03135501],
       [0.97033947, 0.02966053],
       [0.23875257, 0.76124743],
       ...,
       [0.81409863, 0.18590137],
       [0.82534471, 0.17465529],
       [0.15672829, 0.84327171]])

In [33]:
y_pred_class=[]

for value in y_pred_prob[:,1]:
    if value > 0.46:
        y_pred_class.append(1)
        
    else:
        y_pred_class.append(0)
        
print(y_pred_class)        

[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred_class)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,y_pred_class))

acc=accuracy_score(Y_test,y_pred_class)
print("Accuracy of the model : ",acc)

[[6910  513]
 [1208 1138]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.85      0.93      0.89      7423
           1       0.69      0.49      0.57      2346

    accuracy                           0.82      9769
   macro avg       0.77      0.71      0.73      9769
weighted avg       0.81      0.82      0.81      9769

Accuracy of the model :  0.8238304841846658


In [35]:
for a in np.arange(0.4,0.61,0.01):
    predict_mine=np.where(y_pred_prob[:,1]>a,1,0)
    cfm=confusion_matrix(Y_test,predict_mine)
    total_err=cfm[0,1]+cfm[1,0]
    print("Errors at threshold",a,":",total_err," ,type 2 error :",
          cfm[1,0],",type 1 error :",cfm[0,1])

Errors at threshold 0.4 : 1768  ,type 2 error : 1072 ,type 1 error : 696
Errors at threshold 0.41000000000000003 : 1747  ,type 2 error : 1096 ,type 1 error : 651
Errors at threshold 0.42000000000000004 : 1749  ,type 2 error : 1115 ,type 1 error : 634
Errors at threshold 0.43000000000000005 : 1760  ,type 2 error : 1144 ,type 1 error : 616
Errors at threshold 0.44000000000000006 : 1752  ,type 2 error : 1168 ,type 1 error : 584
Errors at threshold 0.45000000000000007 : 1734  ,type 2 error : 1189 ,type 1 error : 545
Errors at threshold 0.4600000000000001 : 1721  ,type 2 error : 1208 ,type 1 error : 513
Errors at threshold 0.4700000000000001 : 1718  ,type 2 error : 1233 ,type 1 error : 485
Errors at threshold 0.4800000000000001 : 1727  ,type 2 error : 1268 ,type 1 error : 459
Errors at threshold 0.4900000000000001 : 1722  ,type 2 error : 1295 ,type 1 error : 427
Errors at threshold 0.5000000000000001 : 1722  ,type 2 error : 1316 ,type 1 error : 406
Errors at threshold 0.5100000000000001 : 1

# using sgd classifier

In [36]:
from sklearn.linear_model import SGDClassifier
#create a fmodel
classifier=SGDClassifier(loss="log",random_state=10,learning_rate="constant",
                          eta0=0.00001,max_iter=1000,shuffle=True,
                         early_stopping=True,n_iter_no_change=5)
#fitting training data to the model
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)
#print(List(zip(Y_test,Y_pred)))
#print(List(zip(adult_df_rev.columns[:-1],classifier.coef_.ravel())))
#print(classifier.intercept)

In [37]:
classifier.n_iter_ # total epochs

6

In [38]:
classifier.t_ # total number of iterations

136753.0

In [39]:
X_train.shape

(22792, 12)

In [40]:
 from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[6632  791]
 [1052 1294]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.86      0.89      0.88      7423
           1       0.62      0.55      0.58      2346

    accuracy                           0.81      9769
   macro avg       0.74      0.72      0.73      9769
weighted avg       0.80      0.81      0.81      9769

Accuracy of the model :  0.8113420002047292


# running model using cross validation

In [41]:
#Using cross validation

classifier=LogisticRegression()

#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10)
#print(k fold_cv)

from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,
                                 y=Y_train,cv=kfold_cv)
print(kfold_cv_result)

#finding the mean
print(kfold_cv_result.mean())

[0.81842105 0.81403509 0.81790259 0.85037297 0.8293111  0.82492321
 0.80824923 0.8174638  0.83106626 0.82843352]
0.8240178825739205


In [42]:
#model tuning

for train_value,test_value in kfold_cv.split(X_train):
    classifier.fit(X_train[train_value],Y_train[train_value]).predict(X_train[test_value])

    Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[7016  407]
 [1315 1031]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7423
           1       0.72      0.44      0.54      2346

    accuracy                           0.82      9769
   macro avg       0.78      0.69      0.72      9769
weighted avg       0.81      0.82      0.81      9769

Accuracy of the model :  0.8237281195618794


# Testing data

In [44]:
test_df=pd.read_csv(r'adult_test.csv',header=None,delimiter=' *, *')
test_df.head()


0          1       2             3   4                   5   \
0  25    Private  226802          11th   7       Never-married   
1  38    Private   89814       HS-grad   9  Married-civ-spouse   
2  28  Local-gov  336951    Assoc-acdm  12  Married-civ-spouse   
3  44    Private  160323  Some-college  10  Married-civ-spouse   
4  18          ?  103497  Some-college  10       Never-married   

                  6          7      8       9     10  11  12             13  \
0  Machine-op-inspct  Own-child  Black    Male     0   0  40  United-States   
1    Farming-fishing    Husband  White    Male     0   0  50  United-States   
2    Protective-serv    Husband  White    Male     0   0  40  United-States   
3  Machine-op-inspct    Husband  Black    Male  7688   0  40  United-States   
4                  ?  Own-child  White  Female     0   0  30  United-States   

       14  
0  <=50K.  
1  <=50K.  
2   >50K.  
3   >50K.  
4  <=50K.

In [45]:
test_df.columns=['age','workclass','fnlwgt','education','education_num',
                  'marital status','occupation','relationship',
                  'race','sex','capital gain','capital_loss',
                  'hours_per_week','native_country','income']

In [46]:
test_df.head()

age  workclass  fnlwgt     education  education_num      marital status  \
0   25    Private  226802          11th              7       Never-married   
1   38    Private   89814       HS-grad              9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm             12  Married-civ-spouse   
3   44    Private  160323  Some-college             10  Married-civ-spouse   
4   18          ?  103497  Some-college             10       Never-married   

          occupation relationship   race     sex  capital gain  capital_loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours_per_week native_country  income  
0              40  United-States  <=50K.  
1              50  United-States  <=50K.  
2              40  United-States   >50K.  
3              40  United-States   >50K.  
4              30  United-States  <=50K.

In [47]:
test_df=test_df.drop(["education","fnlwgt"],axis=1)


In [48]:
test_df.isnull().sum()

age               0
workclass         0
education_num     0
marital status    0
occupation        0
relationship      0
race              0
sex               0
capital gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [49]:
test_df_new=test_df.replace(["?"],np.nan) 

In [50]:
test_df_new.isnull().sum()

age                 0
workclass         963
education_num       0
marital status      0
occupation        966
relationship        0
race                0
sex                 0
capital gain        0
capital_loss        0
hours_per_week      0
native_country    274
income              0
dtype: int64

In [51]:
#replace the missing values with mode values
for value in ['workclass','occupation','native_country']:
    test_df_new[value].fillna(test_df_new[value].mode()[0],inplace=True )

In [52]:
test_df_new.isnull().sum()

age               0
workclass         0
education_num     0
marital status    0
occupation        0
relationship      0
race              0
sex               0
capital gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [53]:
colname=[]
for x in test_df_new.columns:
    if test_df_new[x].dtype=='object':
        colname.append(x)
colname        
     

['workclass',
 'marital status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [54]:
#for preprocessing the data
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
"""
-It will try storing all of the unique values from that (colname)
variable as the key and it will try associating numeric value 
along with it.
-Those number values that assign, are going to be in ascending order.
"""
for x in colname:
    test_df_new[x]=le.fit_transform(test_df_new[x])
    
    le_name_mapping=dict(zip(le.classes_, le.transform(le.classes_)))
    print('feature',x)
    print('mapping',le_name_mapping)

feature workclass
mapping {'Federal-gov': 0, 'Local-gov': 1, 'Never-worked': 2, 'Private': 3, 'Self-emp-inc': 4, 'Self-emp-not-inc': 5, 'State-gov': 6, 'Without-pay': 7}
feature marital status
mapping {'Divorced': 0, 'Married-AF-spouse': 1, 'Married-civ-spouse': 2, 'Married-spouse-absent': 3, 'Never-married': 4, 'Separated': 5, 'Widowed': 6}
feature occupation
mapping {'Adm-clerical': 0, 'Armed-Forces': 1, 'Craft-repair': 2, 'Exec-managerial': 3, 'Farming-fishing': 4, 'Handlers-cleaners': 5, 'Machine-op-inspct': 6, 'Other-service': 7, 'Priv-house-serv': 8, 'Prof-specialty': 9, 'Protective-serv': 10, 'Sales': 11, 'Tech-support': 12, 'Transport-moving': 13}
feature relationship
mapping {'Husband': 0, 'Not-in-family': 1, 'Other-relative': 2, 'Own-child': 3, 'Unmarried': 4, 'Wife': 5}
feature race
mapping {'Amer-Indian-Eskimo': 0, 'Asian-Pac-Islander': 1, 'Black': 2, 'Other': 3, 'White': 4}
feature sex
mapping {'Female': 0, 'Male': 1}
feature native_country
mapping {'Cambodia': 0, 'Canada'

In [55]:
test_df_new.head()

age  workclass  education_num  marital status  occupation  relationship  \
0   25          3              7               4           6             3   
1   38          3              9               2           4             0   
2   28          1             12               2          10             0   
3   44          3             10               2           6             0   
4   18          3             10               4           9             3   

   race  sex  capital gain  capital_loss  hours_per_week  native_country  \
0     2    1             0             0              40              37   
1     4    1             0             0              50              37   
2     4    1             0             0              40              37   
3     2    1          7688             0              40              37   
4     4    0             0             0              30              37   

   income  
0       0  
1       0  
2       1  
3       1  
4       0

In [56]:
X_test_new=test_df_new.values[:,0:-1] #--> 0 to -2
Y_test_new=test_df_new.values[:,-1]

In [57]:
X_test_new=scaler.transform(X_test_new)

In [58]:
X_test_new

array([[-0.99570562, -0.08529633, -1.19745882, ..., -0.21665953,
        -0.03542945,  0.09624323],
       [-0.04264203, -0.08529633, -0.42005962, ..., -0.21665953,
         0.77446821,  0.09624323],
       [-0.77576787, -1.89169231,  0.74603917, ..., -0.21665953,
        -0.03542945,  0.09624323],
       ...,
       [-0.04264203, -0.08529633,  1.13473876, ..., -0.21665953,
         0.77446821,  0.09624323],
       [ 0.39723348, -0.08529633,  1.13473876, ..., -0.21665953,
        -0.03542945,  0.09624323],
       [-0.26257978,  0.81790166,  1.13473876, ..., -0.21665953,
         1.58436587,  0.09624323]])

In [59]:
#store the predicted probabilities
y_pred_prob_new=classifier.predict_proba(X_test_new)
y_pred_prob_new

array([[0.97856006, 0.02143994],
       [0.79066424, 0.20933576],
       [0.69523615, 0.30476385],
       ...,
       [0.50514381, 0.49485619],
       [0.19172259, 0.80827741],
       [0.47101263, 0.52898737]])

In [60]:
y_pred_class_new=[]

for value in y_pred_prob_new[:,1]:
    if value > 0.46:
        y_pred_class_new.append(1)
        
    else:
        y_pred_class_new.append(0)
        
print(y_pred_class_new)   

[0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 

In [61]:

cfm_new=confusion_matrix(Y_test_new,y_pred_class_new)
print(cfm_new)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test_new,y_pred_class_new))

test_acc=accuracy_score(Y_test_new,y_pred_class_new)
print("Accuracy of the test model : ",acc)

[[11526   909]
 [ 1964  1882]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.85      0.93      0.89     12435
           1       0.67      0.49      0.57      3846

    accuracy                           0.82     16281
   macro avg       0.76      0.71      0.73     16281
weighted avg       0.81      0.82      0.81     16281

Accuracy of the test model :  0.8237281195618794
