In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
cars_train=pd.read_csv(r"car_train.csv",header=None)
cars_train.head()


0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [3]:
cars_train.shape

(1382, 7)

In [4]:
cars_test=pd.read_csv(r"car_test.csv",header=None)
cars_test.head()

0      1      2  3      4     5      6
0  low  vhigh  5more  2    med  high  unacc
1  low  vhigh  5more  2    big   low  unacc
2  low  vhigh  5more  2    big   med  unacc
3  low  vhigh  5more  2    big  high  unacc
4  low  vhigh  5more  4  small   low  unacc

In [5]:
cars_test.shape

(346, 7)

In [6]:
cars_train.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]
cars_test.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]

In [7]:
cars_train.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [8]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    low  vhigh  5more       2      med   high   unacc
1    low  vhigh  5more       2      big    low   unacc
2    low  vhigh  5more       2      big    med   unacc
3    low  vhigh  5more       2      big   high   unacc
4    low  vhigh  5more       4    small    low   unacc

# preprocessing

In [9]:
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [10]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [11]:
cars_test.drop("classes",axis=1,inplace=True)
cars_test.head()

buying  maint  doors persons lug_boot safety
0    low  vhigh  5more       2      med   high
1    low  vhigh  5more       2      big    low
2    low  vhigh  5more       2      big    med
3    low  vhigh  5more       2      big   high
4    low  vhigh  5more       4    small    low

In [12]:
col_name=cars_train.columns
col_name

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [13]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in col_name:
    cars_train[x]=le.fit_transform(cars_train[x])
    
    le_name_mapping=dict(zip(le.classes_, le.transform(le.classes_)))
    print('feature',x)
    print('mapping',le_name_mapping)


feature buying
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
feature maint
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
feature doors
mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
feature persons
mapping {'2': 0, '4': 1, 'more': 2}
feature lug_boot
mapping {'big': 0, 'med': 1, 'small': 2}
feature safety
mapping {'high': 0, 'low': 1, 'med': 2}
feature classes
mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [14]:
#feature classes
#mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}

In [15]:
cars_train.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [16]:
col_name=cars_test.columns
col_name

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [17]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in col_name:
    cars_test[x]=le.fit_transform(cars_test[x])

In [18]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       0      3      3        0         1       0
1       0      3      3        0         0       1
2       0      3      3        0         0       2
3       0      3      3        0         0       0
4       0      3      3        1         2       1

In [19]:
X=cars_train.values[:,:-1]
Y=cars_train.values[:,-1]

In [20]:
Y=Y.astype(int)

In [21]:
X.shape

(1382, 6)

In [22]:
Y.shape

(1382,)

In [23]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)

X=scaler.transform(X)


In [24]:
#print(X)

In [25]:
from sklearn.model_selection import train_test_split

#split the data into train test

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

# Running the decision tree model

In [26]:
#predicting the decision tree classifier

from sklearn.tree import DecisionTreeClassifier

#DT_model=DecisionTreeClassifier(criterion="gini",random_state=10,min_samples_leaf=5,max_depth=10)
DT_model=DecisionTreeClassifier(criterion="gini",random_state=10)
#fit the model on the data and predict the values
DT_model.fit(X_train,Y_train)
Y_pred=DT_model.predict(X_test)
print(Y_pred)
#print(list(zip(Y_test,Y_pred)))


[2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 3 0 2 2 2 2 2 2 2 2 2 2 0 2 2
 2 3 2 0 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 2 0 2 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 0 2 0 2 0
 2 0 0 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 0
 2 2 2 0 3 2 2 2 2 0 2 0 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 0 2 3 2
 0 2 2 2 0 2 2 2 2 2 0 2 2 2 0 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2
 0 2 0 2 0 2 2 2 0 2 2 2 2 0 2 2 2 0 2 0 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 3 0
 2 2 2 0 2 0 2 2 2 3 0 3 2 2 2 2 2 2]


In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 52   0   3   0]
 [  0   1   0   0]
 [  1   0 213   0]
 [  0   0   0   7]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        55
           1       1.00      1.00      1.00         1
           2       0.99      1.00      0.99       214
           3       1.00      1.00      1.00         7

    accuracy                           0.99       277
   macro avg       0.99      0.99      0.99       277
weighted avg       0.99      0.99      0.99       277

Accuracy of the model :  0.9855595667870036


In [28]:
DT_model.score(X_train,Y_train)

1.0

In [29]:
print(list(zip(cars_train.columns,DT_model.feature_importances_)))

[('buying', 0.1812886813185831), ('maint', 0.22373174902190068), ('doors', 0.04335871084588105), ('persons', 0.18982581399853654), ('lug_boot', 0.10466082963065837), ('safety', 0.2571342151844403)]


In [30]:
from sklearn import tree
with open("DT_model.txt","w") as f:
    
    f=tree.export_graphviz(DT_model,feature_names=cars_train.columns[:-1],
                              out_file=f)
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [31]:
#? DecisionTreeClassifier

# Support Vector

In [32]:
from sklearn.svm import SVC

svc_model=SVC(kernel="rbf",C=100,gamma=0.1)
svc_model.fit(X_train,Y_train)

Y_pred=svc_model.predict(X_test)
print(list(Y_pred))


[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 3, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 3, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 0, 0, 3, 2, 2, 2, 2, 2, 2]


In [33]:
svc_model.score(X_train,Y_train)

1.0

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 55   0   0   0]
 [  0   1   0   0]
 [  0   0 214   0]
 [  1   0   0   6]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        55
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00       214
           3       1.00      0.86      0.92         7

    accuracy                           1.00       277
   macro avg       1.00      0.96      0.98       277
weighted avg       1.00      1.00      1.00       277

Accuracy of the model :  0.9963898916967509


# KNN

In [35]:
(np.sqrt(len(X_train)))

33.24154027718932

In [36]:
#predicting using the KNeighbors_classifer
from sklearn.neighbors import KNeighborsClassifier

model_KNN=KNeighborsClassifier(n_neighbors=10,
                               metric='euclidean')
#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

#prediction
Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 41   0  14   0]
 [  1   0   0   0]
 [ 13   0 201   0]
 [  7   0   0   0]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.66      0.75      0.70        55
           1       0.00      0.00      0.00         1
           2       0.93      0.94      0.94       214
           3       0.00      0.00      0.00         7

    accuracy                           0.87       277
   macro avg       0.40      0.42      0.41       277
weighted avg       0.85      0.87      0.86       277

Accuracy of the model :  0.8736462093862816


C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,40):
    model_KNN=KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    model_KNN.fit(X_train,Y_train)
    Y_pred=model_KNN.predict(X_test)
    print("Accuracy is",[accuracy_score(Y_test,Y_pred)],"for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is [0.7942238267148014] for K-Value: 1
Accuracy is [0.8303249097472925] for K-Value: 2
Accuracy is [0.8916967509025271] for K-Value: 3
Accuracy is [0.8664259927797834] for K-Value: 4
Accuracy is [0.8772563176895307] for K-Value: 5
Accuracy is [0.8483754512635379] for K-Value: 6
Accuracy is [0.8736462093862816] for K-Value: 7
Accuracy is [0.8628158844765343] for K-Value: 8
Accuracy is [0.8844765342960289] for K-Value: 9
Accuracy is [0.8736462093862816] for K-Value: 10
Accuracy is [0.8736462093862816] for K-Value: 11
Accuracy is [0.8628158844765343] for K-Value: 12
Accuracy is [0.8592057761732852] for K-Value: 13
Accuracy is [0.8592057761732852] for K-Value: 14
Accuracy is [0.8664259927797834] for K-Value: 15
Accuracy is [0.8592057761732852] for K-Value: 16
Accuracy is [0.851985559566787] for K-Value: 17
Accuracy is [0.8411552346570397] for K-Value: 18
Accuracy is [0.8483754512635379] for K-Value: 19
Accuracy is [0.8592057761732852] for K-Value: 20
Accuracy is [0.862815884476534

In [39]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

3 : 0.8916967509025271


In [40]:
from sklearn.linear_model import LogisticRegression
#creating a model
classifier=LogisticRegression()

#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))


[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 0), (2, 0), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (0, 2), (2, 0), (2, 2), (2, 2), (2, 0), (0, 0), (2, 2), (2, 0), (2, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (0, 0), (2, 2), (0, 2), (0, 2), (2, 2), (1, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2),

In [41]:
from sklearn.linear_model import LogisticRegression
#creating a model
classifier=LogisticRegression()

#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))


In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 13   0  42   0]
 [  0   0   1   0]
 [ 19   0 195   0]
 [  4   0   3   0]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.36      0.24      0.29        55
           1       0.00      0.00      0.00         1
           2       0.81      0.91      0.86       214
           3       0.00      0.00      0.00         7

    accuracy                           0.75       277
   macro avg       0.29      0.29      0.29       277
weighted avg       0.70      0.75      0.72       277

Accuracy of the model :  0.7509025270758123


C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\akshay0909\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Testing data

In [43]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       0      3      3        0         1       0
1       0      3      3        0         0       1
2       0      3      3        0         0       2
3       0      3      3        0         0       0
4       0      3      3        1         2       1

In [44]:
test=cars_test.values[:,:]
test=scaler.transform(test)
print(test)

[[-1.33377813e+00  1.23205495e+00  1.37207811e+00 -1.21922350e+00
  -2.65912623e-03 -1.22585334e+00]
 [-1.33377813e+00  1.23205495e+00  1.37207811e+00 -1.21922350e+00
  -1.22762994e+00 -8.86372624e-04]
 [-1.33377813e+00  1.23205495e+00  1.37207811e+00 -1.21922350e+00
  -1.22762994e+00  1.22408059e+00]
 ...
 [-1.33377813e+00 -5.19693960e-01  1.37207811e+00  1.22807770e+00
  -1.22762994e+00 -8.86372624e-04]
 [-1.33377813e+00 -5.19693960e-01  1.37207811e+00  1.22807770e+00
  -1.22762994e+00  1.22408059e+00]
 [-1.33377813e+00 -5.19693960e-01  1.37207811e+00  1.22807770e+00
  -1.22762994e+00 -1.22585334e+00]]


In [45]:
#predicting the decision tree classifier

from sklearn.tree import DecisionTreeClassifier

#DT_model=DecisionTreeClassifier(criterion="gini",random_state=10,min_samples_leaf=5,max_depth=10)
DT_model=DecisionTreeClassifier(criterion="gini",random_state=10)
#fit the model on the data and predict the values
DT_model.fit(X_train,Y_train)


DecisionTreeClassifier(random_state=10)

In [46]:
test_pred=DT_model.predict(test)
test_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0,
       0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0,
       2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2,
       2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0,
       2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [47]:
cars_test['Pred']=test_pred
cars_test.head()

buying  maint  doors  persons  lug_boot  safety  Pred
0       0      3      3        0         1       0     2
1       0      3      3        0         0       1     2
2       0      3      3        0         0       2     2
3       0      3      3        0         0       0     2
4       0      3      3        1         2       1     2

In [48]:
cars_test.to_excel("Decison Test Output.xlsx",header=True)

In [50]:
#predicting the random forest classifier

from sklearn.ensemble import RandomForestClassifier

RF_model=RandomForestClassifier(n_estimators=100,random_state=10)
#fit the model on the data and predict the values
RF_model.fit(X_train,Y_train)
Y_pred=RF_model.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 53   0   2   0]
 [  0   1   0   0]
 [  2   0 212   0]
 [  1   0   0   6]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.95      0.96      0.95        55
           1       1.00      1.00      1.00         1
           2       0.99      0.99      0.99       214
           3       1.00      0.86      0.92         7

    accuracy                           0.98       277
   macro avg       0.98      0.95      0.97       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model :  0.9819494584837545


In [52]:
#predicting the extra tree classifier

from sklearn.ensemble import ExtraTreesClassifier

ET_model=ExtraTreesClassifier(n_estimators=200,random_state=10)
#fit the model on the data and predict the values
ET_model.fit(X_train,Y_train)
Y_pred=ET_model.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 51   0   4   0]
 [  0   1   0   0]
 [  1   0 213   0]
 [  0   0   0   7]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        55
           1       1.00      1.00      1.00         1
           2       0.98      1.00      0.99       214
           3       1.00      1.00      1.00         7

    accuracy                           0.98       277
   macro avg       0.99      0.98      0.99       277
weighted avg       0.98      0.98      0.98       277

Accuracy of the model :  0.9819494584837545


# Ensemble model

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

#creating sub models
estimators=[]
#model_1=LogisticRegression()
#estimators.append(("log",model_1))

model_2=DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(("DT",model_2))

#tuned svc
model_3=SVC(kernel="rbf",C=100,gamma=0.1)
estimators.append(("svm",model_3))

#model_4=KNeighborsClassifier(n_neighbors=11,metric='euclidean')
#estimators.append(("knn",model_4))



In [68]:
#creating the ensemble moodel
ensemble=VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)

Y_pred=ensemble.predict(X_test)
print(Y_pred)

[2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 0 2 2 2 2 2 3 0 2 2 2 2 2 2 2 2 2 2 0 2 2
 2 3 2 0 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 2 0 2 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 0 2 0 2 0
 2 0 0 2 1 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 0
 2 2 2 0 3 2 2 2 2 0 2 0 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 0 2 3 2
 0 2 2 2 0 2 2 2 2 2 0 2 2 2 0 0 0 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2
 0 2 0 2 0 2 2 2 0 2 2 2 2 0 2 2 2 0 2 0 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 3 0
 2 2 2 0 2 0 2 2 2 0 0 3 2 2 2 2 2 2]


In [69]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)


print("CLASSIFICATION REPORT: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model : ",acc)

[[ 55   0   0   0]
 [  0   1   0   0]
 [  1   0 213   0]
 [  1   0   0   6]]
CLASSIFICATION REPORT: 
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        55
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00       214
           3       1.00      0.86      0.92         7

    accuracy                           0.99       277
   macro avg       0.99      0.96      0.98       277
weighted avg       0.99      0.99      0.99       277

Accuracy of the model :  0.9927797833935018
